config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  resources :custom_fields_defaults, only: [:create]
end

app/models/custom_fields_default.rb
class CustomFieldsDefault < ActiveRecord::Base
  belongs_to :project
  belongs_to :custom_field

  validates_presence_of :project, :custom_field

  def customized; end
end

app/controllers/custom_fields_defaults_controller.rb
class CustomFieldsDefaultsController < ApplicationController
  layout 'admin'

  before_action :find_project

  def create
    @value = @project.build_custom_fields_default
    @value.attributes = project_field_params['custom_fields_default_attributes']
    flash[:notice] = l(:notice_successful_update) if @value.save
    respond_to do |format|
      format.html { redirect_to controller: 'projects', action: 'settings', id: @project, tab: params[:tab] }
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def project_field_params
    params.require(:project).permit(
      custom_fields_default_attributes: [:id, :project_id, :custom_field_id, :value]
    )
  end
end

app/views/projects/_custom_fields_deafult_settings.html.erb
<div class="box">
  <%= form_tag project_custom_fields_defaults_path(@project.id), method: 'post', id: 'form_project_custom_fields_defaults_setting' do %>
    <%= hidden_field_tag(:tab, 'custom_fields_default_settings') %>
    <%= l(:label_custom_field) %>:   
    <%= select_tag 'project[custom_fields_default_attributes][custom_field_id]', 
      options_from_collection_for_select(
        TimeEntryCustomField.all, 'id', 'name', 
        @project.custom_fields_default ? @project.custom_fields_default.custom_field_id : 0
      ), id: 'default_custom_field'
    %>
    <p></p>
    <%= l(:field_default_value) %>:
    </p>
    <% if @project.custom_fields_default %>
    </p>   
      <%= radio_button_tag 'project[custom_fields_default_attributes][value]', '', @project.custom_fields_default.value.blank? %>
      <%= l(:label_none) %>
      <% @project.custom_fields_default.custom_field.enumerations.active.each do |element| %>
        </p>
        <%= radio_button_tag 'project[custom_fields_default_attributes][value]', element.id, 
          @project.custom_fields_default.value == element.id.to_s
        %>
        <%= element.name %>
      <% end %>
    <% end %>  
    </p>    
    <%= submit_tag(l(:button_save)) %>
  <% end %>
</div>

<%= javascript_tag do %>
  $(document).ready(function(){
    $("#default_custom_field").change(function () {
      $("#form_project_custom_fields_defaults_setting").submit();
    })    
  });
<% end %>

app/views/time_log/_edit_form_bottom_hook.html.erb
<% if @project.custom_fields_default && @project.custom_fields_default.value.present? %>  
   <%= javascript_tag do %>
    $(document).ready(function(){
      $("input[name='time_entry[custom_field_values][<%= billable_custom_field_id %>]']:radio:not(:checked)").attr('disabled', true);
    });
  <% end %> 
<% end %>